[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "./start.sh"

[phases.setup]
nixPkgs = ["wkhtmltopdf"]

[variables]
DATABASE_URL = "${{ Postgres.DATABASE_URL }}"
# You need to set these values in Railway's dashboard
# TELEGRAM_BOT_TOKEN = "your_bot_token"
# TELEGRAM_CHAT_ID = "your_chat_id" 