[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port=${PORT} --timeout-keep-alive 75"
restartPolicyType = "on_failure"
healthcheckPath = "/up"
healthcheckTimeout = 300
healthcheckInterval = 45
numReplicas = 1 